# Gruvbox Dark colors for tmux

set -g pane-border-style "fg=#504945"
set -g pane-active-border-style "fg=#d79921"

set -g status-style "bg=#282828,fg=#ebdbb2"

set -g status-left "#[bg=#d79921,fg=#282828,bold] #S #[bg=#282828] "
set -g status-right "#[fg=#928374]#[fg=#d3869b,bold] %H:%M #[fg=#504945]| #[fg=#8ec07c]%d-%b-%Y "

setw -g window-status-format "#[fg=#928374] #I:#W "
setw -g window-status-current-format "#[bg=#3c3836,fg=#d79921,bold] #I:#W "

set -g message-style "bg=#282828,fg=#d79921,bold"
set -g message-command-style "bg=#282828,fg=#d3869b"

setw -g mode-style "bg=#3c3836,fg=#ebdbb2"
