alias d="date +'%Y-%m-%d %H:%M'"
alias grep='grep --color=auto'
alias fgrep='fgrep --color=auto'
alias egrep='egrep --color=auto'
alias vi='vim'
alias v='vagrant'
alias gs='git status'
alias gc='git commit'
alias gp='git pull'
alias gl='git log'
alias ga='git add'
alias gpu='git push'
