#!/bin/bash

# vim stuff
if [ ! -h "$HOME/.vim" ] ; then
    ln -s $HOME/.dotfiles/.vim $HOME/.vim
fi

if [ ! -h "$HOME/.vimrc" ] ; then
    ln -s $HOME/.dotfiles/.vim/vimrc $HOME/.vimrc
fi

if [ ! -h "$HOME/.vimrc.local" ] ; then
    ln -s $HOME/.dotfiles/.vimrc.local $HOME/.vimrc.local
fi

if [ ! -h "$HOME/.gvimrc" ] ; then
    ln -s $HOME/.dotfiles/.vim/gvimrc $HOME/.gvimrc
fi

if [ ! -h "$HOME/.gvimrc.local" ] ; then
    ln -s $HOME/.dotfiles/.gvimrc.local $HOME/.gvimrc.local
fi

# git stuff
if [ ! -h "$HOME/.gitconfig" ] ; then
    ln -s $HOME/.dotfiles/.gitconfig $HOME/.gitconfig
fi

# ssh stuff
if [ ! -h "$HOME/.ssh/config" ] ; then
    ln -s $HOME/.dotfiles/.ssh/config $HOME/.ssh/config
fi

if [ ! -h "$HOME/.ssh/enviornment" ] ; then
    ln -s $HOME/.dotfiles/.ssh/config $HOME/.ssh/enviornment
fi

# screen stuff
if [ ! -h "$HOME/.screenrc" ] ; then
    ln -s $HOME/.dotfiles/.screenrc $HOME/.screenrc
fi

# bash stuff
if [ ! -h "$HOME/.bash_profile" ] ; then
    if [ -f "$HOME/.bash_profile" ] ; then
        mv $HOME/.bash_profile $HOME/.bash_profile.bak
    fi
    ln -s $HOME/.dotfiles/.bash_profile $HOME/.bash_profile
fi
if [ ! -h "$HOME/.bashrc" ] ; then
    if [ -f "$HOME/.bashrc" ] ; then
        mv $HOME/.bashrc $HOME/.bashrc.bak
    fi
    ln -s $HOME/.dotfiles/.bashrc $HOME/.bashrc
fi
if [ ! -h "$HOME/.bashrc" ] ; then
    if [ -f "$HOME/.bashrc" ] ; then
        mv $HOME/.bashrc $HOME/.bashrc.bak
    fi
    ln -s $HOME/.dotfiles/.bashrc $HOME/.bashrc
fi
if [ ! -h "$HOME/.bash_aliases" ] ; then
    if [ -f "$HOME/.bash_aliases" ] ; then
        mv $HOME/.bash_aliases $HOME/.bash_aliases.bak
    fi
    ln -s $HOME/.dotfiles/.bash_aliases $HOME/.bash_aliases
fi
if [ ! -h "$HOME/.bashrc_darwin" ] ; then
    if [ -f "$HOME/.bashrc_darwin" ] ; then
        mv $HOME/.bashrc_darwin $HOME/.bashrc_darwin.bak
    fi
    ln -s $HOME/.dotfiles/.bashrc_darwin $HOME/.bashrc_darwin
fi
if [ ! -h "$HOME/.bashrc_linux" ] ; then
    if [ -f "$HOME/.bashrc_linux" ] ; then
        mv $HOME/.bashrc_linux $HOME/.bashrc_linux.bak
    fi
    ln -s $HOME/.dotfiles/.bashrc_linux $HOME/.bashrc_linux
fi
