# Tokyo Night colors for tmux

set -g pane-border-style "fg=#3b4261"
set -g pane-active-border-style "fg=#7aa2f7"

set -g status-style "bg=#1a1b26,fg=#c0caf5"

set -g status-left "#[bg=#7aa2f7,fg=#1a1b26,bold] #S #[bg=#1a1b26] "
set -g status-right "#[fg=#565f89]#[fg=#bb9af7,bold] %H:%M #[fg=#3b4261]| #[fg=#7dcfff]%d-%b-%Y "

setw -g window-status-format "#[fg=#565f89] #I:#W "
setw -g window-status-current-format "#[bg=#283457,fg=#7aa2f7,bold] #I:#W "

set -g message-style "bg=#1a1b26,fg=#7aa2f7,bold"
set -g message-command-style "bg=#1a1b26,fg=#bb9af7"

setw -g mode-style "bg=#283457,fg=#c0caf5"
